INSERT INTO `site`(`id`, `Libelle`, `Adresse`, `CodePostal`, `Ville`, `Telephone`, `Fax`) VALUES
(1,"Champerret","60 rue Laugier","75017","Paris","0142679106",""),
(2,"Marcel Sembat","108 avenue Edouard Vaillant","92100","Boulogne-Billancourt","0141101105",""),
(3,"Cannes","6 place de la Gare","06400","0493303030","",""),
(4,"Chalons sur Saone","","","","",""),
(5,"Hotel de Ville","23 rue du Renard","75004","Paris","0158393131",""),
(6,"Nice","18 avenue Thiers","06000","Nice","0492000808",""),
(7,"Porte d'Orléans","111 avenue du Général Leclerc","75014","Paris","0140434100",""),
(8,"Voltaire","115 boulevard Voltaire","75011","Paris","0140095880",""),
(9,"Keter","10 rue Valenciennes","75010","Paris","0185730303","");



INSERT INTO `fournisseur` (`id`, `nom`, `adresse`, `ville`, `codepostal`, `telephone`) VALUES
(1, '3M ESPE', NULL, NULL, NULL, NULL),
(2, 'Anthogyr', NULL, NULL, NULL, NULL),
(3, 'Pierre Rolland', NULL, NULL, NULL, NULL),
(4, 'R&S', NULL, NULL, NULL, NULL),
(5, 'Terumo', NULL, NULL, NULL, NULL),
(6, 'Browne', NULL, NULL, NULL, NULL),
(7, 'Hawo', NULL, NULL, NULL, NULL),
(8, 'Medibase', NULL, NULL, NULL, NULL),
(9, 'Nichrominox', NULL, NULL, NULL, NULL),
(10, 'Sans marque', NULL, NULL, NULL, NULL),
(11, 'B/braun', NULL, NULL, NULL, NULL),
(12, 'Clinix', NULL, NULL, NULL, NULL),
(13, 'Ethicon', NULL, NULL, NULL, NULL),
(14, 'Hygitech', NULL, NULL, NULL, NULL),
(15, 'Omnia', NULL, NULL, NULL, NULL),
(16, 'Satelec', NULL, NULL, NULL, NULL),
(17, 'Dentsply', NULL, NULL, NULL, NULL),
(18, 'Gc', NULL, NULL, NULL, NULL),
(19, 'Itena', NULL, NULL, NULL, NULL),
(20, 'Kerr', NULL, NULL, NULL, NULL),
(21, 'Produits dentaires', NULL, NULL, NULL, NULL),
(22, 'Voco', NULL, NULL, NULL, NULL),
(23, 'Kem-dent', NULL, NULL, NULL, NULL),
(24, 'Lactona', NULL, NULL, NULL, NULL),
(25, 'Prodont holliger', NULL, NULL, NULL, NULL),
(26, 'Econ', NULL, NULL, NULL, NULL),
(27, 'Hager & werken', NULL, NULL, NULL, NULL),
(28, 'Premier', NULL, NULL, NULL, NULL),
(29, 'Roeko', NULL, NULL, NULL, NULL),
(30, 'Ss white', NULL, NULL, NULL, NULL),
(31, 'Cma', NULL, NULL, NULL, NULL),
(32, 'Dentoclic itena', NULL, NULL, NULL, NULL),
(33, 'Dentsply maillefer', NULL, NULL, NULL, NULL),
(34, 'Micro-mega', NULL, NULL, NULL, NULL),
(35, 'Vmk', NULL, NULL, NULL, NULL),
(36, 'Ems', NULL, NULL, NULL, NULL),
(37, 'Dentoria', NULL, NULL, NULL, NULL),
(38, 'Diatech', NULL, NULL, NULL, NULL),
(39, 'Edenta', NULL, NULL, NULL, NULL),
(40, 'Hu-friedy', NULL, NULL, NULL, NULL),
(41, 'Ivoclar vivadent', NULL, NULL, NULL, NULL),
(42, 'Larident', NULL, NULL, NULL, NULL),
(43, 'Polydentia', NULL, NULL, NULL, NULL),
(44, 'Prima dental', NULL, NULL, NULL, NULL),
(45, 'Dento-viractis', NULL, NULL, NULL, NULL),
(46, 'Durr dental', NULL, NULL, NULL, NULL),
(47, 'Gamasonic', NULL, NULL, NULL, NULL),
(48, 'Aesculap', NULL, NULL, NULL, NULL),
(49, 'Apeco', NULL, NULL, NULL, NULL),
(50, 'Chicago Dental', NULL, NULL, NULL, NULL),
(51, 'Medical Dental pacific', NULL, NULL, NULL, NULL),
(52, 'Ortho plus', NULL, NULL, NULL, NULL),
(53, 'Cyanolit', NULL, NULL, NULL, NULL),
(54, 'Astek', NULL, NULL, NULL, NULL),
(55, 'Ultradent', NULL, NULL, NULL, NULL),
(56, 'Evasion pro', NULL, NULL, NULL, NULL),
(57, 'Reliance', NULL, NULL, NULL, NULL),
(58, 'Vita', NULL, NULL, NULL, NULL),
(59, 'Sopro', NULL, NULL, NULL, NULL),
(60, 'Bausch', NULL, NULL, NULL, NULL),
(61, 'Coltene', NULL, NULL, NULL, NULL),
(62, 'Dr endres', NULL, NULL, NULL, NULL),
(63, 'Depro', NULL, NULL, NULL, NULL),
(64, 'Directal dental', NULL, NULL, NULL, NULL),
(65, 'Molnlycke', NULL, NULL, NULL, NULL),
(66, 'Orsing', NULL, NULL, NULL, NULL),
(67, 'Inibsa', NULL, NULL, NULL, NULL),
(68, 'Archimed', NULL, NULL, NULL, NULL),
(69, 'Septodont', NULL, NULL, NULL, NULL),
(70, 'Hygenic', NULL, NULL, NULL, NULL),
(71, 'Anios', NULL, NULL, NULL, NULL),
(72, 'Oral B', NULL, NULL, NULL, NULL),
(73, 'Sdi', NULL, NULL, NULL, NULL),
(74, 'Steriblue', NULL, NULL, NULL, NULL),
(75, 'Miltex', NULL, NULL, NULL, NULL),
(76, 'Dux', NULL, NULL, NULL, NULL),
(77, 'Swedent', NULL, NULL, NULL, NULL),
(78, 'Bien air', NULL, NULL, NULL, NULL),
(79, 'Cattani', NULL, NULL, NULL, NULL),
(80, 'E.V.E', NULL, NULL, NULL, NULL),
(81, 'Mani', NULL, NULL, NULL, NULL),
(82, 'Schulke', NULL, NULL, NULL, NULL),
(83, 'Diadent', NULL, NULL, NULL, NULL),
(84, 'Svenska Dentorama', NULL, NULL, NULL, NULL),
(85, 'Heraeus kulzer', NULL, NULL, NULL, NULL),
(86, 'Nexa dental', NULL, NULL, NULL, NULL),
(87, 'Dentsply rinn', NULL, NULL, NULL, NULL),
(88, 'Pulpdent', NULL, NULL, NULL, NULL),
(89, 'Tret', NULL, NULL, NULL, NULL),
(90, 'Isp', NULL, NULL, NULL, NULL),
(91, 'Aluwax', NULL, NULL, NULL, NULL),
(92, 'Ortho technology', NULL, NULL, NULL, NULL),
(93, 'Ionyx', NULL, NULL, NULL, NULL),
(94, 'Ivory', NULL, NULL, NULL, NULL),
(95, 'Vdw', NULL, NULL, NULL, NULL),
(96, 'Nsk', NULL, NULL, NULL, NULL),
(97, 'Strauss', NULL, NULL, NULL, NULL),
(98, 'Thomas', NULL, NULL, NULL, NULL),
(99, 'Twindent', NULL, NULL, NULL, NULL),
(100, 'Bactinyl', NULL, NULL, NULL, NULL),
(101, 'Dentsplyash', NULL, NULL, NULL, NULL),
(102, 'Gestenco', NULL, NULL, NULL, NULL),
(103, 'G&H', NULL, NULL, NULL, NULL),
(104, 'Glenroe', NULL, NULL, NULL, NULL),
(105, 'Swann-morton', NULL, NULL, NULL, NULL),
(106, 'Crosstex', NULL, NULL, NULL, NULL),
(107, 'Medistock', NULL, NULL, NULL, NULL),
(108, 'Papernet', NULL, NULL, NULL, NULL);







INSERT INTO `categorie`(`nom`) VALUES
("Anesthesie"),
("Chaine de stérélisation"),
("Chirurgie"),
("Ciments et fonds de cavité"),
("Cires"),
("Empreintes"),
("Endodontie"),
("Equipement"),
("Fraises,polissage et grattage"),
("Hygiène"),
("Instruments"),
("Orthodontie"),
("Preparation de modeles"),
("Prevention, motivation, prophy"),
("protection personne/équipement"),
("Prothèses"),
("Radiographie"),
("Restauration"),
("Tenons"),
("Usage Unique"),
("Photographie)");
